"""phase 2 trend engine: geographic scope, cross-source dedup, source rate limiting

Written by hand rather than left as autogenerated because the generated version would
drop ``collected_at`` (losing data) and add NOT NULL columns with no server default
(failing on any non-empty table).

Revision ID: 0002
Revises: 0001
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- trend_sources: geography, bounded caching and failure backoff --------
    op.add_column("trend_sources", sa.Column("region", sa.String(length=16), nullable=True))
    op.add_column(
        "trend_sources",
        sa.Column("min_interval_minutes", sa.Integer(), nullable=False, server_default="60"),
    )
    op.add_column(
        "trend_sources", sa.Column("next_allowed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "trend_sources",
        sa.Column("consecutive_failures", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("trend_sources", "min_interval_minutes", server_default=None)
    op.alter_column("trend_sources", "consecutive_failures", server_default=None)

    # --- trending_topics ------------------------------------------------------
    # Rename rather than drop+add: the timestamp is the same fact under a clearer name.
    op.alter_column("trending_topics", "collected_at", new_column_name="discovered_at")
    op.add_column("trending_topics", sa.Column("region", sa.String(length=16), nullable=True))
    op.add_column("trending_topics", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.add_column("trending_topics", sa.Column("duplicate_of_id", sa.UUID(), nullable=True))
    op.add_column(
        "trending_topics",
        sa.Column("corroboration_count", sa.Integer(), nullable=False, server_default="1"),
    )

    # Backfill: rows discovered before this migration keep their per-source identity as
    # their content hash. They therefore never cross-match, which is the safe direction —
    # a wrong merge would silently hide a distinct story. They gain cross-source
    # deduplication the next time their source is scanned.
    op.execute("UPDATE trending_topics SET content_hash = dedupe_hash WHERE content_hash IS NULL")
    op.alter_column("trending_topics", "content_hash", nullable=False)
    op.alter_column("trending_topics", "corroboration_count", server_default=None)

    op.create_foreign_key(
        "fk_trending_topics_duplicate_of_id_trending_topics",
        "trending_topics",
        "trending_topics",
        ["duplicate_of_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.drop_index("ix_trending_topics_channel_collected", table_name="trending_topics")
    op.create_index(
        "ix_trending_topics_channel_discovered", "trending_topics", ["channel_id", "discovered_at"]
    )
    op.create_index(
        "ix_trending_topics_channel_content", "trending_topics", ["channel_id", "content_hash"]
    )
    op.create_index(
        "ix_trending_topics_channel_score", "trending_topics", ["channel_id", "opportunity_score"]
    )
    op.create_index("ix_trending_topics_source_kind", "trending_topics", ["source_kind"])
    op.create_index("ix_trending_topics_content_hash", "trending_topics", ["content_hash"])
    op.create_index("ix_trending_topics_discovered_at", "trending_topics", ["discovered_at"])
    op.create_index("ix_trending_topics_duplicate_of_id", "trending_topics", ["duplicate_of_id"])
    op.create_index("ix_trending_topics_region", "trending_topics", ["region"])

    # --- topic_candidates: freshness derived from evidence --------------------
    op.add_column(
        "topic_candidates",
        sa.Column("evidence_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "topic_candidates",
        sa.Column(
            "evidence_source_kinds",
            sa.dialects.postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column(
        "topic_candidates", sa.Column("newest_evidence_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "topic_candidates", sa.Column("oldest_evidence_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("topic_candidates", "evidence_count", server_default=None)
    op.alter_column("topic_candidates", "evidence_source_kinds", server_default=None)


def downgrade() -> None:
    for column in ("oldest_evidence_at", "newest_evidence_at", "evidence_source_kinds", "evidence_count"):
        op.drop_column("topic_candidates", column)

    for index in (
        "ix_trending_topics_region",
        "ix_trending_topics_duplicate_of_id",
        "ix_trending_topics_discovered_at",
        "ix_trending_topics_content_hash",
        "ix_trending_topics_source_kind",
        "ix_trending_topics_channel_score",
        "ix_trending_topics_channel_content",
        "ix_trending_topics_channel_discovered",
    ):
        op.drop_index(index, table_name="trending_topics")
    op.create_index(
        "ix_trending_topics_channel_collected", "trending_topics", ["channel_id", "discovered_at"]
    )
    op.drop_constraint(
        "fk_trending_topics_duplicate_of_id_trending_topics", "trending_topics", type_="foreignkey"
    )
    for column in ("corroboration_count", "duplicate_of_id", "content_hash", "region"):
        op.drop_column("trending_topics", column)
    op.alter_column("trending_topics", "discovered_at", new_column_name="collected_at")

    for column in ("consecutive_failures", "next_allowed_at", "min_interval_minutes", "region"):
        op.drop_column("trend_sources", column)
